//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Tecaj.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecaj
    {
        public int ID { get; set; }
        public Nullable<decimal> Srednji_Tecaj { get; set; }
        public string Ime { get; set; }
    }
}
